# Generated by Django 3.1.5 on 2021-02-27 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0025_remove_author_genre'),
        ('books', '0009_auto_20210227_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishing', to='directory.publishing', verbose_name='Издательство'),
        ),
    ]
