# Generated by Django 3.1.5 on 2021-02-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_coolmodelbro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(verbose_name='Рейтинг (0-10)'),
        ),
    ]
