# Generated by Django 3.1.5 on 2021-02-27 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20210227_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoolModelBro',
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг (0-10)'),
        ),
    ]
