# Generated by Django 3.1.5 on 2021-02-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20210227_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveIntegerField(verbose_name='Рейтинг (0-10)'),
        ),
    ]
