# Generated by Django 3.1.5 on 2021-01-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=100, verbose_name='Серия')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='first_author',
            field=models.CharField(max_length=50, verbose_name='Первый автор'),
        ),
        migrations.AlterField(
            model_name='author',
            name='second_author',
            field=models.CharField(blank=True, max_length=50, verbose_name='Второй автор'),
        ),
    ]
