# Generated by Django 3.1.5 on 2021-02-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_genre_publishing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='second_author',
        ),
    ]
