# Generated by Django 3.1.5 on 2021-02-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_remove_author_second_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_author',
            new_name='name',
        ),
    ]
