# Generated by Django 3.1.5 on 2021-02-06 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20210206_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
