# Generated by Django 3.1.5 on 2021-02-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_author_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.CharField(max_length=30, verbose_name='Дата рождения'),
        ),
    ]
