# Generated by Django 3.1.5 on 2021-02-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_author_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(max_length=30, null=True, verbose_name='Страна'),
        ),
    ]
