# Generated by Django 3.1.5 on 2021-02-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_auto_20210213_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='main_genre',
            new_name='name',
        ),
    ]
