# Generated by Django 3.1.5 on 2021-02-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_auto_20210213_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='descr',
            field=models.CharField(max_length=300, null=True, verbose_name='Описание'),
        ),
    ]
