# Generated by Django 3.1.5 on 2021-02-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_genre_descr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishing',
            old_name='publishing',
            new_name='name',
        ),
    ]
