# Generated by Django 3.1.5 on 2021-02-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_auto_20210213_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing',
            name='descr',
            field=models.CharField(max_length=300, null=True, verbose_name='Описание'),
        ),
    ]
