# Generated by Django 3.1.5 on 2021-02-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0018_auto_20210213_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='author',
            name='genre',
            field=models.ManyToManyField(to='directory.Genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='descr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
