# Generated by Django 3.1.5 on 2021-02-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0023_auto_20210213_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='genre',
            field=models.ManyToManyField(to='directory.Genre'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='descr',
            field=models.CharField(max_length=100, null=True, verbose_name='Страна'),
        ),
    ]
