# Generated by Django 3.1.5 on 2021-03-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_auto_20210309_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('phone', models.TextField(verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Телефон')),
                ('status', models.TextField(verbose_name='Телефон')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cart.cart', verbose_name='Корзина')),
            ],
        ),
    ]
