# Generated by Django 3.1.5 on 2021-03-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.TextField(blank=True, null=True, verbose_name='Контактное лицо'),
        ),
    ]
