# Generated by Django 3.1.5 on 2021-03-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='summ',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа'),
        ),
    ]
