# Generated by Django 3.1.5 on 2021-03-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210316_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=30, verbose_name='Адрес доставки'),
        ),
    ]
