# Generated by Django 3.1.5 on 2021-03-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsincart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания корзины'),
        ),
        migrations.AddField(
            model_name='goodsincart',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего изменения корзины'),
        ),
        migrations.AlterField(
            model_name='goodsincart',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Книги', to='cart.cart', verbose_name='Корзина'),
        ),
    ]
