# Generated by Django 3.1.5 on 2021-03-09 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210309_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsincart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания корзины'),
        ),
        migrations.AlterField(
            model_name='goodsincart',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Дата последнего изменения корзины'),
            preserve_default=False,
        ),
    ]
