# Generated by Django 3.1.5 on 2021-03-11 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210311_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsincart',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='cart.cart', verbose_name='Корзина'),
        ),
    ]
