# Generated by Django 3.1.5 on 2021-03-13 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20210227_1716'),
        ('cart', '0008_auto_20210313_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsincart',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.book', verbose_name='Книга в корзине'),
        ),
    ]
