# Generated by Django 3.1.5 on 2021-02-17 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('country', models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='Город')),
                ('postcode', models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name='Индекс')),
                ('аddress', models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
