# Generated by Django 3.1.5 on 2021-02-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210217_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.CharField(max_length=20, null=True, verbose_name='Группа'),
        ),
    ]
