# Generated by Django 3.1.5 on 2021-02-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_userprofile_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='group',
        ),
    ]
