# Generated by Django 3.1.5 on 2021-03-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20210302_2357'),
        ('customer', '0010_auto_20210303_2236'),
        ('customer', '0008_auto_20210303_2217'),
    ]

    operations = [
    ]
