# Generated by Django 3.1.5 on 2021-03-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20210303_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='аddress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес'),
        ),
    ]
